### ISSUE TITLE
Linux deb fails to launch due to DRM

### ISSUE THREAD

**Issue by inygaard-iteris** [franciscoBSalgueiro/en-croissant#136]
### Describe the bug

```
[2024-02-03][17:09:56][WARN][PP@tauri://localhost/assets/index.js:265:3540] Invalid value for tabs: null
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x569: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x569: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x569: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```
Searching, looks the same as this issue: https://github.com/elementary/browser/discussions/104. Workaround for me is to set `WEBKIT_DISABLE_DMABUF_RENDERER=1` environment variable. Apparently using a newer version of a webkit may fix this.

### Reproduction

1. Install latest deb on ubuntu
2. Try to run

### Platform and versions

Ubuntu 22.04, encroissant 0.8.0

**Comment by Azmisov** [comment]
Tried installing from source and same error

**Comment by franciscoBSalgueiro** [comment]
The issue is with webkitgtk, which GNOME Web (browser of elementaryOS) also uses. I don't think there's much I can do. You need to either update to a newer version of webkitgtk or set that env variable. 

Other env variables that might help with webkit related issues:
 `WEBKIT_DISABLE_DMABUF_RENDERER=1`
`WEBKIT_DISABLE_COMPOSITING_MODE=1`
