### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by woprandi** [franciscoBSalgueiro/en-croissant#284]
### Describe the bug

I tried to  build from sources today but it failed immediately :

### Reproduction

pnpm install && pnpm build

### Platform and versions

Fedora 40
pnpm 8.12.0
NodeJS 20.12.2

### Stack trace

```Shell
$ pnpm build

> en-croissant@0.10.0 build /home/william/Documents/Repos/en-croissant
> tauri build -b none

       Error failed to get cargo metadata: No such file or directory (os error 2)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by franciscoBSalgueiro** [comment]
You have to install the Tauri requirements as well as it says in the README.

https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux

**Comment by fwn0** [comment]
I have this problems .....

♻  Regenerating routes...
✅ Processed routes in 59ms
✓ 8307 modules transformed.
warnings when minifying css:
▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9077:37:
      9077 │   [data-mantine-color-scheme="dark"] & {
           ╵                                      ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9080:38:
      9080 │   [data-mantine-color-scheme="light"] & {
           ╵                                       ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9088:37:
      9088 │   [data-mantine-color-scheme="dark"] & {
           ╵                                      ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9091:38:
      9091 │   [data-mantine-color-scheme="light"] & {
           ╵                                       ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9103:37:
      9103 │   [data-mantine-color-scheme="dark"] & {
           ╵                                      ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9106:38:
      9106 │   [data-mantine-color-scheme="light"] & {
           ╵                                       ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9501:37:
      9501 │   [data-mantine-color-scheme="dark"] & {
           ╵                                      ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


▲ [WARNING] Transforming this CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:9504:38:
      9504 │   [data-mantine-color-scheme="light"] & {
           ╵                                       ^

  The nesting transform for this case must generate an ":is(...)" but the configured target environment does not support the ":is" pseudo-class.


dist/index.html            0.29 kB │ gzip:     0.20 kB
dist/assets/index.css    258.95 kB │ gzip:    37.20 kB
dist/assets/index.js   3,685.44 kB │ gzip: 1,119.43 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 29.21s
error: invalid character `{` in package name: `tauri-plugin-{{name}}`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
 --> ../../../../../../.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/d95a1b3/shared/template/Cargo.toml:2:8
  |
2 | name = "tauri-plugin-{{name}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^
  |
error: failed to download `ring v0.17.8`

Caused by:
  unable to get packages from source

Caused by:
  failed to unpack package `ring v0.17.8`

Caused by:
  failed to unpack entry at `ring-0.17.8/third_party/NIST/SHAVS/SHA256LongMsg.rsp`

Caused by:
  failed to unpack `/home/artix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.8/third_party/NIST/SHAVS/SHA256LongMsg.rsp`

Caused by:
  failed to unpack `ring-0.17.8/third_party/NIST/SHAVS/SHA256LongMsg.rsp` into `/home/artix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.8/third_party/NIST/SHAVS/SHA256LongMsg.rsp`

Caused by:
  unexpected end of file
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.

pnpm update was helpless, no successful setup even with bun:

Found 19 errors in 7 files.
Errors  Files
    12  node_modules/@tanstack/react-router/dist/esm/fileRoute.d.ts:10
     1  src/components/boards/BoardAnalysis.tsx:46
     1  src/components/files/FilesPage.tsx:107
     1  src/components/files/Modals.tsx:46
     2  src/components/settings/SettingsPage.tsx:71
     1  src/components/tabs/ConfirmChangesModal.tsx:20
     1  src/components/tabs/ImportModal.tsx:61
 ELIFECYCLE  Command failed with exit code 2.
       Error beforeBuildCommand `pnpm build-vite` failed with exit code 2


pnpm 9.7.0, node 22.5.1, bun 1.1.22
