### ISSUE TITLE
Rework of repertoire practice mode

### ISSUE THREAD

**Issue by sleeplessghost** [franciscoBSalgueiro/en-croissant#58]
Suggestion to rework the practice mode to use a spaced repetition algorithm that factors in things like date solved to determine when positions should next be reviewed. A common one is SM-2 (example implementation: https://github.com/Maxvien/supermemo)

IMO the current workflow is a little clunky as well with needing to click on "Practice next position" / "Practice random position" after each position.

I can try adding this at some point if you would be happy with the change

**Comment by franciscoBSalgueiro** [comment]
Yes that would be great!

Do you think it would be better to move automatically to the next position when you get the move right?

Another problem is that I think it's not super obvious the feature even exists, as you have to mark a file as a Repertoire in order to see the practice options.

**Comment by sleeplessghost** [comment]
> Do you think it would be better to move automatically to the next position when you get the move right?

Yeah I'd prefer it that way, I think its more similar to how other training modes work in chess websites

> Another problem is that I think it's not super obvious the feature even exists, as you have to mark a file as a Repertoire in order to see the practice options.

Some ideas:
- Could have some sort of notification badge on repertoires indicating they have positions to be reviewed with a button to go straight to practice mode (I guess it may need some option in metadata to enable/disable these notifications)
![practicerepertoire](https://github.com/franciscoBSalgueiro/en-croissant/assets/25903992/25bb4528-0b06-4d15-9939-28279d4c1e92)
- Could have a different kind of practice mode for PGNs e.g. "Learn from your mistakes" where it analyzes then shows you positions which have mistakes or blunders in the PGN. Probably no need to persist the results other than temporarily in state

**Comment by franciscoBSalgueiro** [comment]
Those are excellent ideas. That first one would make a lot of sense combined with the spaced repetition algorithm.

**Comment by MrPiada** [comment]
It looks to me that this part of the software is not quite developed, am I right ? I'm asking this kindly to avoid opening issues on that specific stuff. 
If you prefer to have precise feedbacks I'm happy to document them and opening issues and discussing UX related choices.

**Comment by franciscoBSalgueiro** [comment]
Please do, I want to improve this in the future.

**Comment by MrPiada** [comment]
I'm using this simple pgn as test:

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[Orientation "white"]

1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. b4 Bxb4  (4... Bb6  5. a4 a5 6. b5) 5. c3 Bc5 6. d4 exd4 7. O-O *
```

## UX improvements

### Usage
I understood that the user should:
- press "practice next position"
- make a move
- press "practice next position"
- make a move
...
and so on

To me this is quite unusable or at least very slow cause of the very high number of clicks needed.
I think that the user experience should be the one implemented in chessable where you have a line and the user takes a part (black or white) and execute its move while the other part is automatically executed just following the line answers.
Some remarks/improvement on this journey:

- [ ] **Variation choice**: having a file with a main line and several nested variations would be nice that the algorithm can chose randomly the variation in each branching point (this could be improved by not be fully random but, for example, following the database frequence of the move....so that you study more often the variations that are more likely to happen OR, another approach, could be selecting the variations that are more often played wrongly when studying them)

- [ ] having at least the possibility of making the moves from both sides (I really would like to reduce as much as possible the number of clicks on buttons and the "practice next position" is quite superflous to me)

### UI improvements

- [ ] add a symbol to the files tab that shows which of them are practice files like the one proposed in the[ previous comment](https://github.com/franciscoBSalgueiro/en-croissant/issues/58#issuecomment-1777691469)

- [ ] create a tab for practice and put it as the first default choice when opening a training file so that is at least 1 click closer:
<img width="945" alt="Screenshot 2024-02-17 alle 15 55 52" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/32706712/3d62b243-d8a7-4ba9-867d-5dfa967d1f20">

- [ ] (this one is going to be pretty huge but I'd love it) the [chessquid](https://www.chessquid.com/) software (whose development I think has been almost abandoned) implements a quite original representation of the lines:
<img width="632" alt="Screenshot 2024-02-17 alle 15 59 31" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/32706712/dd399a22-48bb-4858-968b-3e29d4293674">

regarding the practice mode would be pretty funny to color each node of this tree respect to the success/attemp ration in guessing the move so the immediately one can visualize where he/she making more mistakes in learning the repertoire


## BUG: 
Here:
<img width="1429" alt="Screenshot 2024-02-17 alle 15 47 08" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/32706712/3c74a510-615d-4a4f-9082-f26c87256fea">

if I click on "practice next position" the knight goes back on the g1 square, I move it to f3 and press the "practice next position" but knight still goes to g2 and I'm not moving along with the variation.
